In [28]:
from tensorflow.keras.preprocessing.text import one_hot

In [29]:
#pip install distutils

In [30]:
#pip install tensorflow

In [31]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [32]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [33]:
#vocabulary_Size
voc_size=10000

In [34]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [35]:
one_hot_repr

[[7267, 2583, 1365, 9718],
 [7267, 2583, 1365, 8153],
 [7267, 2449, 1365, 1203],
 [6625, 3948, 1585, 7979, 795],
 [6625, 3948, 1585, 7979, 1059],
 [3317, 7267, 2612, 1365, 386],
 [6003, 6226, 2963, 7979]]

In [42]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [43]:
import numpy as np

In [44]:
sent_length=8
pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

array([[   0,    0,    0,    0, 7267, 2583, 1365, 9718],
       [   0,    0,    0,    0, 7267, 2583, 1365, 8153],
       [   0,    0,    0,    0, 7267, 2449, 1365, 1203],
       [   0,    0,    0, 6625, 3948, 1585, 7979,  795],
       [   0,    0,    0, 6625, 3948, 1585, 7979, 1059],
       [   0,    0,    0, 3317, 7267, 2612, 1365,  386],
       [   0,    0,    0,    0, 6003, 6226, 2963, 7979]], dtype=int32)

In [49]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7267 2583 1365 9718]
 [   0    0    0    0 7267 2583 1365 8153]
 [   0    0    0    0 7267 2449 1365 1203]
 [   0    0    0 6625 3948 1585 7979  795]
 [   0    0    0 6625 3948 1585 7979 1059]
 [   0    0    0 3317 7267 2612 1365  386]
 [   0    0    0    0 6003 6226 2963 7979]]


In [50]:
## Feature Representation

dim=10

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [54]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [55]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [56]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[-0.03083037,  0.04064823, -0.00095856, -0.02312158,
          0.04454166, -0.03484613,  0.02998276,  0.03305704,
          0.01654543,  0.02481605],
        [-0.03083037,  0.04064823, -0.00095856, -0.02312158,
          0.04454166, -0.03484613,  0.02998276,  0.03305704,
          0.01654543,  0.02481605],
        [-0.03083037,  0.04064823, -0.00095856, -0.02312158,
          0.04454166, -0.03484613,  0.02998276,  0.03305704,
          0.01654543,  0.02481605],
        [-0.03083037,  0.04064823, -0.00095856, -0.02312158,
          0.04454166, -0.03484613,  0.02998276,  0.03305704,
          0.01654543,  0.02481605],
        [ 0.04112751,  0.04611852,  0.0431857 , -0.0065329 ,
          0.01467087,  0.03578648,  0.01059574,  0.00093077,
         -0.02016157,  0.00339497],
        [ 0.03146614,  0.03935382,  0.04063727, -0.0080515 ,
         -0.03142133,  0.03225925,  0.01803682, -0.04322488,
         -0.0087657 , -0.03672918],
        [ 0.02588635, -0.0051272 , -0.02972577,  0.0

In [57]:
embedded_docs[0]

array([   0,    0,    0,    0, 7267, 2583, 1365, 9718], dtype=int32)

In [58]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None