In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8186, 2997, 1021, 7982],
 [8186, 2997, 1021, 4898],
 [8186, 3195, 1021, 8747],
 [6681, 8289, 8451, 5148, 6619],
 [6681, 8289, 8451, 5148, 2246],
 [4139, 8186, 6638, 1021, 6096],
 [4082, 5515, 8037, 5148]]

In [6]:

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [16]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8186 2997 1021 7982]
 [   0    0    0    0 8186 2997 1021 4898]
 [   0    0    0    0 8186 3195 1021 8747]
 [   0    0    0 6681 8289 8451 5148 6619]
 [   0    0    0 6681 8289 8451 5148 2246]
 [   0    0    0 4139 8186 6638 1021 6096]
 [   0    0    0    0 4082 5515 8037 5148]]


In [8]:
## feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
voc_size = 10000  # Example vocabulary size
dim = 50  # Example embedding dimension
sent_length = 100  # Length of each input sentence
